In [ ]:
# Imported libraries for data cleaning

from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# Loaded the used car dataset
df=pd.read_csv("/content/quikr_car.csv")
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [ ]:
# Displayed first 5 rows
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [ ]:
df.shape

(892, 6)

In [ ]:
# Viewed all column names
df.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='object')

In [ ]:
# Checked data types of each column
df.dtypes

name          object
company       object
year          object
Price         object
kms_driven    object
fuel_type     object
dtype: object

In [ ]:
# Identified missing values in each column
df.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [ ]:
# Counted duplicate rows
df.duplicated().sum()

np.int64(94)

In [ ]:
# Viewed dataset structure and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [ ]:
# Created a copy to preserve the original dataset
car = df.copy()

In [ ]:
# Standardized column names to lowercase and removed extra spaces
car.columns = car.columns.str.strip().str.lower().str.replace(' ', '_')
car.head()

,name,company,year,price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [ ]:
# Removed leading and trailing spaces from text columns
car = car.apply(
    lambda col: col.str.strip() if col.dtype == 'object' else col
)
car.head()

,name,company,year,price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [ ]:
# Removed duplicate rows from the dataset
car = car.drop_duplicates().copy()

# Checked updated dataset size
car.shape

(798, 6)

In [ ]:
# Rechecked missing values after duplicate removal
car.isnull().sum()

name           0
company        0
year           0
price          0
kms_driven    50
fuel_type     53
dtype: int64

In [ ]:
# Checked the most frequent values in the year column
car['year'].value_counts(dropna=False).head(15)

year
2015    93
2014    86
2013    75
2016    71
2012    63
2011    56
2009    52
2017    50
2010    42
2018    32
2006    21
2019    20
2007    17
2008    15
2005    13
Name: count, dtype: int64

In [ ]:
# Converted year values to numeric and invalid entries to NaN
car['year'] = pd.to_numeric(car['year'], errors='coerce')

In [ ]:
# Checked price values to identify invalid text entries
car['price'].value_counts(dropna=False).head(15)

price
Ask For Price    33
2,50,000         14
3,50,000         13
1,30,000         12
1,80,000         11
3,00,000         11
1,50,000         11
4,50,000         11
4,00,000         11
2,20,000         10
1,20,000         10
85,000            9
1,10,000          9
95,000            9
1,60,000          9
Name: count, dtype: int64

In [ ]:
# Removed commas and extra spaces from price values
car['price'] = car['price'].astype(str).str.replace(',', '', regex=False).str.strip()

# Replaced "Ask For Price" with missing values
car['price'] = car['price'].replace('Ask For Price', np.nan)

# Converted price values to numeric
car['price'] = pd.to_numeric(car['price'], errors='coerce')

In [ ]:
# Checked values in the kilometres-driven column
car['kms_driven'].value_counts(dropna=False).head(15)

kms_driven
NaN           50
45,000 kms    28
35,000 kms    26
55,000 kms    20
50,000 kms    19
40,000 kms    18
60,000 kms    18
20,000 kms    17
41,000 kms    15
30,000 kms    15
65,000 kms    14
38,000 kms    13
42,000 kms    12
39,000 kms    12
70,000 kms    12
Name: count, dtype: int64

In [ ]:
# Removed commas, kms text and extra spaces
car['kms_driven'] = (
    car['kms_driven']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('kms', '', case=False, regex=False)
    .str.strip()
)

# Converted kilometres driven to numeric
car['kms_driven'] = pd.to_numeric(car['kms_driven'], errors='coerce')

In [ ]:
# Checked fuel type categories and missing values
car['fuel_type'].value_counts(dropna=False)

fuel_type
Petrol    402
Diesel    341
NaN        53
LPG         2
Name: count, dtype: int64

In [ ]:
# Filled missing numerical values with column medians
car['year'] = car['year'].fillna(car['year'].median())
car['price'] = car['price'].fillna(car['price'].median())
car['kms_driven'] = car['kms_driven'].fillna(car['kms_driven'].median())

# Filled missing categorical values with "Unknown"
car['fuel_type'] = car['fuel_type'].fillna('Unknown')
car['name'] = car['name'].fillna('Unknown')
car['company'] = car['company'].fillna('Unknown')

In [ ]:
# Reviewed year range and statistical summary
car['year'].describe()

count     798.000000
mean     2012.444862
std         4.017383
min      1995.000000
25%      2010.000000
50%      2013.000000
75%      2015.000000
max      2019.000000
Name: year, dtype: float64

In [ ]:
# Displayed the first 5 rows of cleaned data
car.head()

,name,company,year,price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000.0,45000.0,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006.0,425000.0,40.0,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018.0,290000.0,22000.0,Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000.0,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000.0,Diesel

In [ ]:
# Verified data types after cleaning
car.dtypes

name           object
company        object
year          float64
price         float64
kms_driven    float64
fuel_type      object
dtype: object

In [ ]:
# Checked whether any missing values remain
car.isnull().sum()

name          0
company       0
year          0
price         0
kms_driven    0
fuel_type     0
dtype: int64

In [ ]:
# Verified duplicate rows after cleaning
car.duplicated().sum()

np.int64(0)

In [ ]:
# Kept only the first two words from each car name
car['name'] = car['name'].apply(
    lambda x: ' '.join(str(x).split()[:2]) if pd.notna(x) else x
)

# Viewed the updated car names
car['name'].head(10)

0    Hyundai Santro
1     Mahindra Jeep
2     Maruti Suzuki
3     Hyundai Grand
4     Ford EcoSport
5     Ford EcoSport
6         Ford Figo
7       Hyundai Eon
8     Ford EcoSport
9     Maruti Suzuki
Name: name, dtype: object

In [ ]:
# Replaced the original dataframe with the cleaned data
df = car.copy()

# Viewed the updated main dataset
df.head()

             name   company    year     price  kms_driven fuel_type
0  Hyundai Santro   Hyundai  2007.0   80000.0     45000.0    Petrol
1   Mahindra Jeep  Mahindra  2006.0  425000.0        40.0    Diesel
2   Maruti Suzuki    Maruti  2018.0  290000.0     22000.0    Petrol
3   Hyundai Grand   Hyundai  2014.0  325000.0     28000.0    Petrol
4   Ford EcoSport      Ford  2014.0  575000.0     36000.0    Diesel

In [ ]:
# Saved the cleaned main dataset
df.to_csv('/content/quikr_car.csv', index=False)